package com.flexyquiz.app.client.core.mvp;

import com.google.gwt.place.shared.Place;
import com.google.gwt.place.shared.PlaceHistoryMapper;

// stub implementation; actually generated by PlaceHistoryMapperGenerator
public class GeneratedPlaceHistoryMapper implements PlaceHistoryMapper {
  public Place getPlace(String token) {
    return null;
  }

  public String getToken(Place place) {
    return null;
  }  
}
