package com.flexyquiz.app.client.core.mvp;

// stub implementation; actually generated by ViewRegistryGenerator
public class GeneratedViewRegistry implements ViewRegistry {
  public BaseDisplay getView(BaseActivity activity) {
    return null;
  }
}
